# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f1d4d70b93e876ca83aeed44cde037b3964be0252f5fe858670d9d69907283cd203d71d23519c7ba97f1b0e0832204e874e898372c56934f9d956a99b535469d

test:
  secret_key_base: e5e53db795febe09cfbd72a4ae981ede42c80dfa9112225c33d5b86193ed943803840c8e309be3ebef6f49089ebc4fb5e6439666ee8317f123b8106c8859c0b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
